[package]
name = "zmatrix"
version = "0.1.6"
edition = "2021"
authors = ["Treagzhao"]
license = "MIT"
description="This is a matrix calculation lib"

[dependencies]
approx = "0.5.1"
serde = "1.0.219"
