[package]
name = "zmatrix"
version = "0.1.10"
edition = "2021"
authors = ["Treagzhao"]
license = "MIT"
description="This is a matrix calculation lib"

[dependencies]
approx = "0.5.1"
lazy_static = "1.5.0"
rand = "0.9.1"
serde = "1.0.219"
